nsd-zone-writer: Properly isolate user permissions
We now use a dedicated user just for writing dynamic zones and we allow
only a list of users specified with allowedUsers to update zones.

The implementation is a bit more involved, because we only allow a
setuid binary to run as the dynzone user and because we can't use the
setuid bit on shell scripts, we use a small wrapper around that.

One of the reasons I'm not using the security.wrappers option but
implement this on my own is that we want our wrapper to be as simple as
possible without propagating *any* environment variables and without any
magic around figuring out the target binary from a common path.

I'm also using more strict permissions on everything related to the zone
writer, so that we only have those permissions set that are absolutely
necessary and nothing more.

To make sure this is the case we now have an extra test exclusively for
the NSD zone file writer.

Tested with the new nsd-zone-writer and the dyndns NixOS VM tests.

Signed-off-by: aszlig <aszlig@redmoonstudios.org>

diff --git a/modules/services/nsd-zone-writer/writer.sh.in b/modules/services/nsd-zone-writer/writer.sh.in
--- a/modules/services/nsd-zone-writer/writer.sh.in
+++ b/modules/services/nsd-zone-writer/writer.sh.in
@@ -1,26 +1,29 @@
-#!@shell@ -e
 fqdn="$1"
-umask 0007
-zonefile="/var/lib/nsd/dynzones/$fqdn.zone"
+umask 0027
+zonefile="@baseDir@/$fqdn.zone"
 
 touchZonefile() {
-    touch -r "$zonefile" -d '1 sec' "$zonefile"
+    @touch@ -r "$zonefile" -d '1 sec' "$zonefile"
 }
 
 if [ -e "$zonefile" ]; then
-    oldMTime="$(stat -c %Y "$zonefile")"
+    oldMTime="$(@stat@ -c %Y "$zonefile")"
     exists=1
 else
     oldMTime=0
     exists=0
 fi
 
-zonedata="$(cat)"
+zonedata="$(@cat@)"
 
-echo "$zonedata" | @checkzone@ "$fqdn" - || exit 1
+if ! zoneErrors="$(echo "$zonedata" | @checkzone@ "$fqdn" - 2>&1)"; then
+    echo "$zoneErrors" >&2
+    exit 1
+fi
+
 echo "$zonedata" > "$zonefile"
 
-if [ "$oldMTime" -eq "$(stat -c %Y "$zonefile")" ]; then
+if [ "$oldMTime" -eq "$(@stat@ -c %Y "$zonefile")" ]; then
     touchZonefile
 fi
 
@@ -62,7 +65,7 @@ for waitTime in 1 2 5 10 30; do
     echo "Reload of $fqdn failed, touching zone file and" \
          "resending reload..." >&2
     touchZonefile
-    read touched <&''${waitForUpdate[0]}
+    read touched <&${waitForUpdate[0]}
     @ctrl@ reload "$fqdn" >&2
 done
 echo "Reloading of zone $fqdn failed after 5 retries." >&2
